Initial structure of Pure virtual class - Vehicle
Uneatablee/Cpp_playground pull request #5
Opened 2023-08-01 14:33 UTC by Uneatablee

2023-08-01 16:17 UTC, Mat3oo requested changes

2023-08-01 16:17 UTC, Mat3oo commented on src/business_logic/bus_stop/include/IVehicle.hpp
There is no built in concept of interfaces in c++, but you can achieve behavior of interfaces with abstract class. 
https://accu.org/journals/overload/12/62/radford_233/

2023-08-01 16:17 UTC, Mat3oo commented on src/business_logic/bus_stop/include/IVehicle.hpp
> +        virtual void IdrawVehicle() = 0;
Interface method name should omit 'I' prefix.

2023-08-08 17:38 UTC, Mat3oo requested changes

2023-08-08 17:38 UTC, Mat3oo commented on src/business_logic/bus_stop/include/Bus_stop_extended.hpp
> +    class Bus_stop_extended : virtual public IBus_stop
If this is base class, name should be `Bus_stop_base` to not be misleading.

2023-08-08 17:38 UTC, Mat3oo commented on src/business_logic/bus_stop/include/Route.hpp
Be consistent with your naming convention. Use _CamelCase_ or _pascalCase_, don't mix them. Most important is to pick one and stick with it :)

2023-08-08 17:38 UTC, Mat3oo commented on src/business_logic/bus_stop/include/Route.hpp
> +        {
Move implementation to cpp file.

2023-08-08 17:38 UTC, Mat3oo commented on src/business_logic/bus_stop/src/Tbus.cpp
> +    void Tbus::moveVehicle(Vehicle_extended::Movement direction)
I can see that this method is common for `Tbus` and `Tcar`, consider to move it to the base class.

2023-08-08 17:38 UTC, Mat3oo commented on src/business_logic/bus_stop/src/Tbus.cpp
> +    Tbus::~Tbus()
Be compliant with rule of 0 or rule of 5. Define rest of compiler generated special methods.
(ref: https://en.cppreference.com/w/cpp/language/rule_of_three)

2023-08-08 17:38 UTC, Mat3oo commented on src/business_logic/bus_stop/src/Tcar.cpp
> +    Tcar::~Tcar()
Be compliant with rule of 0 or rule of 5. Define rest of compiler generated special methods.
(ref: https://en.cppreference.com/w/cpp/language/rule_of_three)

2023-08-08 17:38 UTC, Mat3oo commented on src/business_logic/bus_stop/src/Tstop.cpp
> +    Tstop::~Tstop(){}
Be compliant with rule of 0 or rule of 5. If destructor doing nothing it should not even be defined.
(ref: https://en.cppreference.com/w/cpp/language/rule_of_three)

2023-08-08 17:38 UTC, Mat3oo commented on src/business_logic/bus_stop/src/Tterminal.cpp
> +    Tterminal::~Tterminal(){}
Be compliant with rule of 0 or rule of 5. If destructor doing nothing it should not even be defined.
(ref: https://en.cppreference.com/w/cpp/language/rule_of_three)

2023-08-08 17:38 UTC, Mat3oo commented on src/console/header.hpp
There is a _precompiled header_ concept in c++ ;)
https://learn.microsoft.com/en-us/cpp/build/creating-precompiled-header-files?view=msvc-170

2023-08-08 20:32 UTC, Uneatablee commented on src/business_logic/bus_stop/include/Route.hpp
> +        ~Route()
Changes applied

2023-08-08 20:32 UTC, Uneatablee commented on src/business_logic/bus_stop/include/Bus_stop_extended.hpp
> +    class Bus_stop_extended : virtual public IBus_stop
Changes applied

2023-08-08 20:43 UTC, Uneatablee commented on src/business_logic/bus_stop/include/Route.hpp
Changes applied

2023-08-08 20:43 UTC, Uneatablee commented on src/business_logic/bus_stop/include/Vehicle_extended.hpp
Changes Applied

2023-08-09 21:20 UTC, Uneatablee commented on src/business_logic/bus_stop/src/Tbus.cpp
> +    Tbus::~Tbus()
rule of 0 -> changes applied

2023-08-09 21:21 UTC, Uneatablee commented on src/business_logic/bus_stop/src/Tcar.cpp
> +    Tcar::~Tcar()
rule of 0 changes applied

2023-08-09 21:21 UTC, Uneatablee commented on src/business_logic/bus_stop/src/Tterminal.cpp
> +    Tterminal::~Tterminal(){}
changs applied

2023-08-09 21:21 UTC, Uneatablee commented on src/business_logic/bus_stop/src/Tstop.cpp
> +    Tstop::~Tstop(){}
changes applied

2023-08-09 21:34 UTC, Uneatablee commented on src/business_logic/bus_stop/src/Tbus.cpp
> +    void Tbus::moveVehicle(Vehicle_extended::Movement direction)
changes applied

2023-08-09 21:35 UTC, Uneatablee commented on src/console/header.hpp
added to learning plans

2023-09-07 21:28 UTC, Mat3oo approved these changes

2023-09-07 21:29 UTC, merged